name: .NET Core

on: [push]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test with dotnet
      run: dotnet test
  build-backend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
  build-front:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Angular
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Move to angular directory
      run: cd MOBoard\
    - name: list dir
      run: ls  
    - name: Run NPM install
      run: npm install
    - name: Install angular cli
      run: npm install -g @angular/cli
    - name: Run ng build on production type
      run: ng build --prod
